status_description = {
    1000: 'The request was completed successfully.',
    1001: 'The request was accepted for processing.',
    2000: 'The request is invalid.',
    2001: 'The requested action is forbidden.',
    2002: 'The specified PIN is not recognized.',
    2003: 'The specified web address is invalid.',
    2004: 'The BlackBerry Push Service could not find the specified Push ID.',
    2005: 'The request specifies a function that is not available in the Push Initiator.',
    2006: 'The request specifies a function that the Push Initiator does not support.',
    2007: 'The supplied Push ID is not unique.',
    2008: 'The Push ID is valid, but the push request could not be cancelled.',
    3000: 'The BlackBerry Infrastructure could not complete the request due to an internal error.',
    3001: 'The server does not support the operation that was requested.',
    3002: 'The server does not support the PAP version specified in the request.',
    3003: 'The action can not be completed because the message is no longer available.',
    3004: 'The PPG does not support some Push Initiator capability information provided in the push message.',
    3005: 'The PPG does not support the requested operation for multiple recipients.',
    3006: 'The PPG could not transform the message.',
    3007: 'The PPG could not deliver the message using the specified method.',
    3009: 'The network that was requested is not available.',
    3010: 'The bearer that was requested is not available.',
    3011: 'The PPG does not support the replace operation.',
    4000: 'The service failed.',
    4001: 'The server is busy.',
    4500: 'The request expired.',
    4501: 'The request failed.',
    4502: 'The request failed because the BlackBerry device port number is closed.',
    22000: 'The RIM specific request is badly formed.',
    21000: 'The RIM specific request was completed successfully.',
    22001: 'The BlackBerry Push Service could not find the specified Push ID for the RIM specific request.',
    22002: 'The specified web address in the RIM specific request is invalid.',
    22003: 'The RIM specific request produces an incorrect status.',
    22004: 'The RIM specific request produces no results.',
    22005: 'The RIM specific request exceeds the number of calls allowed within the specified time period.',
    23000: 'The BlackBerry Push Service has an error that prevented the request from being completed.'
}
